name: webapp_template
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6
  jwt_decoder: ^2.0.1
  url_launcher: ^6.3.0
  uuid: ^4.4.2
  json_string: ^3.0.1
  intl: ^0.19.0
  flutter_fancy_tree_view: ^1.6.0
  list_picker: ^1.1.0
  provider: ^6.1.2
  syncfusion_flutter_pdf: ^27.2.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  


  webapp_components:
    git:
      ref: main
      url: git@github.com:tercen/webapp_lib
      path: webapp_components

  webapp_workflow:
    git:
      ref: main
      url: git@github.com:tercen/webapp_lib
      path: webapp_workflow

  sci_tercen_client:
    git:
      ref: 1.3.0
      url: https://github.com/tercen/sci_tercen_client
      path: sci_tercen_client
  

  flutter_lints: ^3.0.0


# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/img/logo.png
    - assets/img/wait.webp
    #- assets/repos.json
    #- assets/umap_settings.json
    #- assets/workflow_steps.json

  fonts:
    - family: RobotMono
      fonts:
        - asset: fonts/RobotoMono-Regular.ttf
